sudo: false

language: ruby

install:
  - bundle install

script:
  - jekyll build --strict_front_matter --safe
  - jekyll doctor --safe

notifications:
  email:
    on_success: never
    on_failure: change
